### ISSUE TITLE
ConsoleSpam&BlockedMessages

### ISSUE THREAD

**Issue by ravenofthewastes** [cnaude/PurpleIRC-spigot#18]
In An Attempt To Set the System up to work, Every 5seconds or so I get spammed with:

[00:02:02] [Server thread/INFO]: [PurpleIRC] [DEBUG] AFK: RavenOfTheWastes:false
[00:02:03] [pool-3-thread-452/INFO]: [PurpleIRC] [DEBUG] [isMessageEnabled] Twitch:game-afk:false
[00:02:05] [pool-3-thread-452/WARN]: Exception in thread "pool-3-thread-452" 
[00:02:05] [pool-3-thread-452/WARN]: org.apache.commons.lang.UnhandledException: Plugin PurpleIRC v1.0-195 generated an exception while executing task 714
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: at index 0
    at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:240)
    at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:231)
    at com.google.common.collect.ImmutableSortedSet.construct(ImmutableSortedSet.java:427)
    at com.google.common.collect.ImmutableSortedSet.copyOf(ImmutableSortedSet.java:357)
    at com.google.common.collect.ImmutableSortedSet.copyOf(ImmutableSortedSet.java:380)
    at com.google.common.collect.ImmutableSortedSet.copyOf(ImmutableSortedSet.java:292)
    at com.cnaude.purpleirc.ext.org.pircbotx.UserChannelMap.getChannels(UserChannelMap.java:77)
    at com.cnaude.purpleirc.ext.org.pircbotx.UserChannelDao.getChannels(UserChannelDao.java:245)
    at com.cnaude.purpleirc.ext.org.pircbotx.User.getChannels(User.java:164)
    at com.cnaude.purpleirc.PurpleBot.getChannels(PurpleBot.java:3431)
    at com.cnaude.purpleirc.PurpleBot.updateNickList(PurpleBot.java:2425)
    at com.cnaude.purpleirc.ChannelWatcher$1.run(ChannelWatcher.java:43)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

If I'm being Blind or something, please help me.

Also, In attempts to Ignore the Spam, I tested messaging and recieved this via debug:

[00:05:48] [listenerPool0-thread10/INFO]: [PurpleIRC] [DEBUG] Broadcast All [irc.message.connect]: [ravnofthewastes] Connected to IRC server.
[00:05:48] [listenerPool0-thread10/INFO]: [PurpleIRC] [DEBUG] Adding message to broadcast queue: [ravnofthewastes] Connected to IRC server.
[00:05:48] [Server thread/INFO]: [ravnofthewastes] Connected to IRC server.[m

[00:05:51] [listenerPool0-thread3/ERROR]: [PurpleIRC] :tmi.twitch.tv 421 ravnofthewastes WHO :Unknown command

[00:33:12] [Timer-0/INFO]: [PurpleIRC] [DEBUG] [0]: queueAndSend message detected
[00:33:12] [Timer-0/INFO]: [PurpleIRC] [DEBUG] [blockingIRCMessage] About to send IRC message to Twitch: [03Wargrounds] <RavenOfTheWastes> say, hangon, forcing a log
[00:33:12] [Timer-0/INFO]: [PurpleIRC] [DEBUG] [blockingIRCMessage] Message sent to Twitch: [03Wargrounds] <RavenOfTheWastes> say, hangon, forcing a log
[00:33:12] [Server thread/INFO]: [m<[0;33;22m[[0;31;1mRaven[0;31;1mCore[0;33;22m] [mRavenOfTheWastes[m> say, hangon, forcing a log[m

Messages Will not appear in either direction, incoming or outgoing from the server.

PluginList
MCCore, SimpleBackUp, WoodCutter, WorldEdit, dtlCore, GroupManager, ClearLag, Vault, ProtocolLib, Citizens, SkillAPI, Denizen, Quests, Essentials, PurpleIRC, EssentialsChat, AutoRank, PlayerVaults, Sentry, EssentialsSpawn, dtlTraders

**Comment by cnaude** [comment]
Please pastebin your bot yml file and startup log. (Remove sensitive info)

**Comment by ravenofthewastes** [comment]
http://pastebin.com/5Q9ky2eP < Server Start Up Log
http://pastebin.com/NH3xcMmQ < Bot

**Comment by ravenofthewastes** [comment]
yes, i left everything >_<

**Comment by cnaude** [comment]
Line 129 of your bot file. Your channel name is invalid. It needs to start with a #.

**Comment by ravenofthewastes** [comment]
Okay... That fixed the Spam, But i still can't get it to go through either way

**Comment by cnaude** [comment]
Can I see the updated debug log now  that it's not throwing errors?

**Comment by ravenofthewastes** [comment]
http://pastebin.com/xFJwhaPt

**Comment by cnaude** [comment]
I did some testing with twitch.tv and purplwirc. The IRC channel must be a valid twitch channel name. It will likely be the same as your twitch account name.

Example:
https://www.twitch.tv/cnaude
IRC nick: cnaude
IRC channe: #cnaude

**Comment by ravenofthewastes** [comment]
example? I thought I had already done that with my twitch id. :ravnofthewastes

**Comment by ravenofthewastes** [comment]
or wait,.,,, instead of #Rtv do #Twitch_Name_here?

**Comment by cnaude** [comment]
Yeah try #ravnofthewastes

**Comment by ravenofthewastes** [comment]
same thing. [blockingircmessage]

**Comment by ravenofthewastes** [comment]
Okay never mind,,, Im just dense and added a space after the id....
