### ISSUE TITLE
Cannot find legacy packet 201

### ISSUE THREAD

**Issue by uncovery** [cnaude/PurpleIRC-spigot#35]
My logfile is getting a lot of task exception errors. They stat when someone is logging in only, then sooner or later, they are all what I can see in my logfile. Doing a /irc reload solves this issue temporarily.
Running latest version of Spigot.
They are all based on the "Cannot find legacy packet 201" issue. Sample error:

`[13:53:05 WARN]: [PurpleIRC] Plugin PurpleIRC v2.1.14-415 generated an exception while executing task 37
java.lang.IllegalArgumentException: Cannot find legacy packet 201
        at com.comphenix.protocol.PacketType.findLegacy(PacketType.java:675) ~[?:?]
        at com.comphenix.protocol.injector.PacketConstructor.withPacket(PacketConstructor.java:117) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.createPacketConstructor(PacketFilterManager.java:897) ~[?:?]
        at com.cnaude.purpleirc.Utilities.NetPackets.tabPacket(NetPackets.java:188) ~[?:?]
        at com.cnaude.purpleirc.Utilities.NetPackets.remFromTabList(NetPackets.java:99) ~[?:?]
        at com.cnaude.purpleirc.PurpleBot.updateNickList(PurpleBot.java:2475) ~[?:?]
        at com.cnaude.purpleirc.PurpleBot.updateNickList(PurpleBot.java:2443) ~[?:?]
        at com.cnaude.purpleirc.ChannelWatcher$1.run(ChannelWatcher.java:43) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-65e8124-79e55b6]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-65e8124-79e55b6]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
`

**Comment by cnaude** [comment]
Please try the latest version of PurpleIRC-spigot. It is 100% compatible with the CraftBukkit servers. https://h.cnaude.org/jenkins/job/PurpleIRC-spigot/lastSuccessfulBuild/artifact/target/PurpleIRC-1.0-306.jar
