### ISSUE TITLE
PurpleIRC not working with venturechat

### ISSUE THREAD

**Issue by MidnightSugar** [cnaude/PurpleIRC-spigot#44]
I keep getting this error whenever I try to chat:

`>.... [23:37:27 ERROR]: Could not pass event AsyncPlayerChatEvent to PurpleIRC v1.0-350
java.lang.IllegalStateException: VentureChatEvent may only be triggered synchronously.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[patched_1.14.4.jar:git-Paper-186]
at com.cnaude.purpleirc.PurpleBot.gameChat(PurpleBot.java:1362) ~[?:?]
at com.cnaude.purpleirc.GameListeners.GamePlayerChatListener.onAsyncPlayerChat(GamePlayerChatListener.java:78) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor300.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-186]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-186]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-186]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-186]
at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1713) ~[patched_1.14.4.jar:git-Paper-186]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1628) ~[patched_1.14.4.jar:git-Paper-186]
at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.14.4.jar:git-Paper-186]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

Using venturechat 2.16.0 and PurpleIRC 1.0-350.

**Comment by cnaude** [comment]
Does the same thing occur with VentureChat 2.17.1?

**Comment by MidnightSugar** [comment]
yes

**Comment by cnaude** [comment]
Please try https://jenkins.chrisnaude.com/jenkins/job/PurpleIRC-spigot/352/artifact/target/PurpleIRC-1.0-352.jar

**Comment by MidnightSugar** [comment]
That fixed the problem, its now working!
