### ISSUE TITLE
Error occurred while disabling PurpleIRC v1.0-353

### ISSUE THREAD

**Issue by harl** [cnaude/PurpleIRC-spigot#45]
Obviously this doesn't hinder PurpleIRC from functioning correctly, as it only happens upon server exit or restart.
From my config.yml: "enable-ident-server: true"
Most of the time my server doesn't forward the necessary ports for the ident server to work properly (or it's closing the sockets too fast, IDK), so the ident mostly doesn't work. Maybe you could add a second check for it upon disabling the plugin, just to prevent this server error.
```
[12:26:28] [Server thread/ERROR]: Error occurred while disabling PurpleIRC v1.0-353 (Is it up to date?)
java.lang.RuntimeException: Never created an IdentServer
	at com.cnaude.purpleirc.ext.org.pircbotx.IdentServer.stopServer(IdentServer.java:96) ~[?:?]
	at com.cnaude.purpleirc.PurpleIRC.onDisable(PurpleIRC.java:424) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-77]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[patched_1.15.2.jar:git-Paper-77]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) ~[patched_1.15.2.jar:git-Paper-77]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:439) ~[patched_1.15.2.jar:git-Paper-77]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:432) ~[patched_1.15.2.jar:git-Paper-77]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:402) ~[patched_1.15.2.jar:git-Paper-77]
	at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:742) ~[patched_1.15.2.jar:git-Paper-77]
	at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:745) ~[patched_1.15.2.jar:git-Paper-77]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Paper-77]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by cnaude** [comment]
Please try https://jenkins.chrisnaude.com/jenkins/job/PurpleIRC-spigot/354/
