### ISSUE TITLE
PurpleIRC For input string: "0;" Error

### ISSUE THREAD

**Issue by BRUTme** [cnaude/PurpleIRC-spigot#49]
This error shows in my console
08:04:43 ERROR]: [PurpleIRC] For input string: "0;"
it seems everything is working even with it, but when I add mcMMO plugin, the chat from IRC server -> Game is not working, this is the error that showed me:

08:04:43 ERROR]: [PurpleIRC] For input string: "0;"
[08:04:43 ERROR]: [PurpleIRC] onMessage: null
[08:04:43 WARN]: java.lang.NullPointerException
[08:04:43 WARN]: at java.base/java.lang.String.replace(String.java:2143)
[08:04:43 WARN]: at com.cnaude.purpleirc.Utilities.ChatTokenizer.ircChatToGameTokenizer(ChatTokenizer.java:221)
[08:04:43 WARN]: at com.cnaude.purpleirc.PurpleBot.broadcastChat(PurpleBot.java:2793)
[08:04:43 WARN]: at com.cnaude.purpleirc.IRCMessageHandler.processMessage(IRCMessageHandler.java:181)
[08:04:43 WARN]: at com.cnaude.purpleirc.IRCListeners.MessageListener.onMessage(MessageListener.java:69)
[08:04:43 WARN]: at com.cnaude.purpleirc.ext.org.pircbotx.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:66)
[08:04:43 WARN]: at com.cnaude.purpleirc.ext.org.pircbotx.hooks.managers.ThreadedListenerManager$1.call(ThreadedListenerManager.java:119)
[08:04:43 WARN]: at com.cnaude.purpleirc.ext.org.pircbotx.hooks.managers.ThreadedListenerManager$1.call(ThreadedListenerManager.java:114)
[08:04:43 WARN]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[08:04:43 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[08:04:43 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[08:04:43 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
[08:05:45 ERROR]: [PurpleIRC] For input string: "0;"

If you want to test, the server is http://mc.BRUT.me

**Comment by cnaude** [comment]
What version of mcMMO are you running?

**Comment by cnaude** [comment]
Please try this test build: https://www.dropbox.com/s/uvy3y1f19e3dchq/PurpleIRC-1.0-SNAPSHOT.jar?dl=0

**Comment by BRUTme** [comment]
Thanx friend, yes this build works, the 0 error is there  but it works with mcMMO, it just puts a empty line between the error message and the text in console

```
> Send: [PurpleIRC] -irc.brut.me-*** Found your hostname
> [22:01:12 INFO]: [PurpleIRC] -irc.brut.me-*** Found your hostname
> [22:01:13 INFO]: [MC_SERVER] Connected to IRC server.
> [22:01:16 INFO]: Send: [PurpleIRC] Joining channel: #MC
> [22:01:16 INFO]: [PurpleIRC] Joining channel: #MC
> [22:01:16 INFO]: [IRC] Brutka +o MC_SERVER on #MC
> [22:06:02 INFO]: Send: [PurpleIRC] For input string: "0;"
> [22:06:02 ERROR]: [PurpleIRC] For input string: "0;"
> [22:06:02 INFO]:
> [22:06:02 INFO]: [IRC]<saradsmejem> test
> [22:06:13 INFO]: Send: [PurpleIRC] For input string: "0;"
> [22:06:13 ERROR]: [PurpleIRC] For input string: "0;"
> [22:06:13 INFO]:
> [22:06:13 INFO]: [IRC]<saradsmejem> test2
```

**Comment by Firepup6500** [comment]
>  it just puts a empty line between the error message and the text in console

It also does this in the chat, which looks really odd.

**Comment by Firepup6500** [comment]
Once done, #60 should fix this. (At least, the blank lines issue, I'm not sure where the "0;" thing comes from)
