### ISSUE TITLE
DiscordSRV 1.22.0 Incompatibility

### ISSUE THREAD

**Issue by selfslaughter** [cnaude/PurpleIRC-spigot#51]
Attempting to send a message from a discord channel throws up a stacktrace with DiscordSRV 1.22.0.

Paper: 1.16.5-581
DiscordSRV: 1.22.0
PurpleIRC: 1.0-358 (latest dev build as of this post)

```
[20:52:11 ERROR]: DiscordSRV API Listener com.cnaude.purpleirc.GameListeners.DiscordListener threw an error
[20:52:11 ERROR]: java.lang.NoSuchMethodError: 'java.util.Map github.scarsz.discordsrv.DiscordSRV.getColors()'
[20:52:11 ERROR]:       at com.cnaude.purpleirc.Utilities.ChatTokenizer.discordChatToIRCTokenizer(ChatTokenizer.java:510)
[20:52:11 ERROR]:       at com.cnaude.purpleirc.PurpleBot.discordChat(PurpleBot.java:1525)
[20:52:11 ERROR]:       at com.cnaude.purpleirc.GameListeners.DiscordListener.onDiscordGuildMessageReceivedEvent(DiscordListener.java:56)
[20:52:11 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:52:11 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:52:11 ERROR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:52:11 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.api.ApiManager.callEvent(ApiManager.java:134)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.listeners.DiscordChatListener.onGuildMessageReceived(DiscordChatListener.java:74)
[20:52:11 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:52:11 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:52:11 ERROR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:52:11 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:411)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:149)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:97)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:956)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:843)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:821)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:994)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
[20:52:11 ERROR]:       at github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)
[20:52:11 INFO]: Global Chat: self_slaughter: :/
```

**Comment by cnaude** [comment]
Please try https://jenkins.chrisnaude.com/jenkins/job/PurpleIRC-spigot/lastSuccessfulBuild/artifact/target/PurpleIRC-1.0-358.jar

**Comment by selfslaughter** [comment]
Yeah, build 359 appears to work well. Thanks for the quick response. :D
