### ISSUE TITLE
Plugin will not load broken with error msg

### ISSUE THREAD

**Issue by kalleswe** [cnaude/PurpleIRC-spigot#55]
[16:46:31 ERROR]: Error occurred while enabling PurpleIRC v1.0-352 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.Plugin.getDescription()" because the return value of "org.bukkit.plugin.PluginManager.getPlugin(String)" is null
        at com.cnaude.purpleirc.PurpleBot.loadConfig(PurpleBot.java:809) ~[?:?]
        at com.cnaude.purpleirc.PurpleBot.<init>(PurpleBot.java:303) ~[?:?]
        at com.cnaude.purpleirc.PurpleIRC.loadBot(PurpleIRC.java:785) ~[?:?]
        at com.cnaude.purpleirc.PurpleIRC.loadBots(PurpleIRC.java:769) ~[?:?]
        at com.cnaude.purpleirc.PurpleIRC.onEnable(PurpleIRC.java:357) ~[?:?]

**Comment by cnaude** [comment]
What version of Spigot is this happening on? Can you post your PurpleIRC/config.yml?
