### ISSUE TITLE
[1.18] java.lang.NoSuchFieldError: WHITESPACE

### ISSUE THREAD

**Issue by Lastorder-DC** [cnaude/PurpleIRC-spigot#56]
```
java.lang.NoSuchFieldError: WHITESPACE
        at com.cnaude.purpleirc.ext.org.pircbotx.Utils.tokenizeLine(Utils.java:106) ~[PurpleIRC-1.0-362.jar:?]
        at com.cnaude.purpleirc.ext.org.pircbotx.InputParser.handleLine(InputParser.java:307) ~[PurpleIRC-1.0-362.jar:?]
        at com.cnaude.purpleirc.ext.org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:282) ~[PurpleIRC-1.0-362.jar:?]
        at com.cnaude.purpleirc.ext.org.pircbotx.PircBotX.connect(PircBotX.java:242) ~[PurpleIRC-1.0-362.jar:?]
        at com.cnaude.purpleirc.ext.org.pircbotx.PircBotX.startBot(PircBotX.java:155) ~[PurpleIRC-1.0-362.jar:?]
        at com.cnaude.purpleirc.PurpleBot$3.run(PurpleBot.java:573) ~[PurpleIRC-1.0-362.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.jar:git-Paper-39]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.jar:git-Paper-39]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.jar:git-Paper-39]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Abve error occurs when trying to use at 1.18 papermc.

**Comment by cnaude** [comment]
Please try https://jenkins.chrisnaude.com/jenkins/job/PurpleIRC-spigot/371/artifact/target/PurpleIRC-1.0-371.jar

**Comment by Lastorder-DC** [comment]
![image](https://user-images.githubusercontent.com/18280396/145388866-2b50e08b-074e-4075-a2c1-9518008129d5.png)
![image](https://user-images.githubusercontent.com/18280396/145388892-75cf90e5-f77c-4501-b1e2-677e11caf91a.png)

Tested, and works fine.
